mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=test
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"
  extra_hosts:
    - "dh:10.0.2.2"